export const HOME_PAGE = "Home";
export const CLAIM_PAGE = "Claim Details";
export const AUTH_PAGE = "Authenticator";
export const SIGNIN_PAGE = "SignIn";
export const HOME_NAVIGATOR = "Home";
export const INCIDENT_PAGE = "Incident Details";
export const CONTACT_PAGE = "Contact Details";
export const INVOLVED_PAGE = "Involved Parties Details";
export const ADDPASSENGER_PAGE = "Add Passenger Details"
export const SUMMARY_PAGE = "Summary";
export const THANKYOU_PAGE ="Thank you";