export const HOME_PAGE = "Home";
export const CLAIM_PAGE = "Car claim details";
export const AUTH_PAGE = "Welcome";
export const SIGNIN_PAGE = "Sign in";
export const HOME_NAVIGATOR = "Home";
export const INCIDENT_PAGE = "Incident details";
export const CONTACT_PAGE = "Contact details";
export const INVOLVED_PAGE = "Involved parties details";
export const ADDPASSENGER_PAGE = "First passenger details"
export const SUMMARY_PAGE = "Summary";
export const THANKYOU_PAGE ="Thank you";